name: Build_Win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task00, task1, task01, task2, task02, task3, task03, task05, task5, task06, task6]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: install glfw
      run: |
        git submodule update --init -- external/glfw
        cd external/glfw
        cmake . -A x64
        cmake --build . --config Release
        cmake --install . --prefix ../glfwlib

    - name: install delfem2
      run: |
        git submodule update --init -- external/delfem2

    - name: get_eigen
      run: |
        git submodule update --init -- external/eigen

    - name: build
      run: |
        cmake . -A x64
        cmake --build .
